# Start with BioSim base image.
ARG BASE_IMAGE=latest@sha256:5eb67b09e3fdf64b3128bd9501e08a0cbb007804b678f2096728d8c1260e6217
FROM ghcr.io/ccpbiosim/jupyterhub-base:$BASE_IMAGE

LABEL maintainer="James Gebbie-Rayet <james.gebbie@stfc.ac.uk>"

# Switch to jovyan user.
USER $NB_USER
WORKDIR $HOME

# Install workshop deps
RUN conda install -y -c conda-forge \
    conda-forge::matplotlib=3.10.8 \
    conda-forge::mdanalysis=2.10.0 \
    conda-forge::numpy=2.5.3 \
    conda-forge::nglview=4.0.1 \
    conda-forge::ipywidgets=8.1.8 \
    conda-forge::gromacs=2025.4=nompi_*
RUN pip install --no-cache-dir \
    mdtraj==1.11.1.post2 \
    vermouth==0.15.0 \
    insane==1.2.0 \
    "setuptools<82" \
    CG2AT-lite==0.3.1

RUN curl -sL -o /tmp/pylipid-1.6.0.tar.gz \
    https://github.com/pstansfeld/PyLipID/archive/refs/tags/v1.6.0.tar.gz \
    && pip install --no-cache-dir /tmp/pylipid-1.6.0.tar.gz \
    && rm /tmp/pylipid-1.6.0.tar.gz

#COPY docker/fix-nglview.sh /tmp/fix-nglview.sh
#RUN bash /tmp/fix-nglview.sh

# Clone workshop contents
COPY --chown=1000:100 . .
RUN rm -rf README.md docker .git .github

# Copy lab workspace
#COPY --chown=1000:100 docker/default-37a8.jupyterlab-workspace /home/jovyan/.jupyter/lab/workspaces/default-37a8.jupyterlab-workspace

# Always finish with non-root user as a precaution.
USER $NB_USER
